version: "3.8"

services:
  redis:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: infra
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: ./api
      dockerfile: Dockerfile  # optional if your Dockerfile is named 'Dockerfile' in context
    ports:
      - "3000:3000" # Map port 3000 inside container to 3000 on host
    depends_on:
      - redis
      - postgres
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres

