[dependencies]
tokio = { version = "1", features = ["full"] }
redis = "0.24"
tokio-postgres = { version = "0.7", features = ["with-uuid-0_8"] }
uuid = { version = "1", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"